# SonarQube Configuration File
sonar.projectKey=10-Pearls-Internship-MERN-Notes-App
sonar.projectName=10-Pearls-Internship-MERN-Notes-App
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000

# Sources & Tests
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.test.inclusions=backend/tests/**/*,frontend/tests/**/*
# Coverage Reports
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
# Exclusions
sonar.coverage.exclusions=**/node_modules/**, **/dist/**, **/*.d.ts, **/coverage/**, **/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.test.ts
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.d.ts, **/coverage/**, **/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.test.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info