// import NotesModel from '../models/NotesModel'
import { logger } from "../utils/logger.js";
import { NotesModel } from "../models/Note.js";
import AppError from "../utils/AppError.js";
import { parsePositiveInt } from "../utils/parsePositiveInt.js";
import { SORT_OPTIONS } from "../constants/SORT.js";

const createNoteService = async (userId, { title, content, tag = "none" }) => {
  const note = await NotesModel.create({
    title,
    content,
    tag,
    user: userId,
  });
  if (!note) {
    throw new AppError("Note could not be created", 404);
  }
  logger.info({ userId, noteId: note._id }, "Note created successfully");
  return note;
};

const getNotesService = async ({ userId, search, sort, page, limit, tag, favorites }) => {

  //helper function to escape special characters in search term
  const escapeRegExp = (string) => {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  };

  // filtering for the authenticated user id
  const filter = { user: userId };
  const searchTerm = search.trim();
  const sortOrder = SORT_OPTIONS[sort] || SORT_OPTIONS.updatedAt_desc;

  const safeLimit = Math.min(parsePositiveInt(limit, 10), 40);
  const safePage = parsePositiveInt(page, 1);

  const skip = (safePage - 1) * safeLimit;

  const escapedSearch = escapeRegExp(searchTerm);

  // Filter by tag if provided (and not "all")
  if (tag && tag !== "all") {
    filter.tag = tag;
  }

  // Filter to show only favorites
  if (favorites === "true" || favorites === true) {
    filter.isFavorite = true;
  }

  //search by title or content using regex
  if (searchTerm) {
    filter.$or = [
      {
        title: {
          $regex: escapedSearch,
          $options: "i", //supports case sensitive
        },
      },
      {
        content: {
          $regex: escapedSearch,
          $options: "i",
        },
      },
    ];
  }

  //finding all notes for the user with specified id and displaying it in latest first form
  const [notes, totalNotes] = await Promise.all([
    // resolving both queries in parallel
    NotesModel.find(filter).limit(safeLimit).skip(skip).sort(sortOrder).lean(), //returns the notes for the current page
    NotesModel.countDocuments(filter), //returns total notes matching the filter
  ]);

  if (!notes) {
    throw new AppError("Notes couldnt be fetched", 404); //404 - not found
  }

  logger.info({ userId }, "All notes returned successfully");

  return {
    notes,
    pagination: {
      page: safePage,
      limit: safeLimit,
      total: totalNotes,
      totalPages: Math.ceil(totalNotes / safeLimit),
    },
  };
};

const getNoteService = async (userId, noteId) => {
  //this query checks if the note exists and belongs to the authenticated user
  const note = await NotesModel.findOne({
    _id: noteId,
    user: userId,
  });

  if (!note) {
    throw new AppError("Note not found", 404);
  }
  logger.info({ userId, noteId }, "Note returned successfully");
  return note;
};

const updateNoteService = async (userId, noteId, { title, content, tag }) => {
  // Build update object – only include tag if explicitly provided
  const updateFields = { title, content };
  if (tag !== undefined) {
    updateFields.tag = tag;
  }

  const updatedNote = await NotesModel.findOneAndUpdate(
    {
      _id: noteId, //automatically generated by mongodb
      user: userId, //part of our schema
    },
    updateFields,
    {
      returnDocument: "after", //returns document after it is updated
      runValidators: true, //runs schema validation for notes
    },
  );

  if (!updatedNote) {
    throw new AppError("Note not found", 404);
  }

  logger.info({ userId, noteId }, "Note updated successfully");

  return updatedNote;
};

const toggleFavoriteService = async (userId, noteId) => {
  // First fetch the note to get current isFavorite value
  const note = await NotesModel.findOne({ _id: noteId, user: userId });
  if (!note) {
    throw new AppError("Note not found", 404);
  }

  const updatedNote = await NotesModel.findOneAndUpdate(
    { _id: noteId, user: userId },
    { isFavorite: !note.isFavorite },
    { returnDocument: "after", runValidators: true },
  );

  logger.info({ userId, noteId, isFavorite: updatedNote.isFavorite }, "Note favorite toggled");
  return updatedNote;
};

const deleteNoteService = async (userId, noteId) => {
  const deletedNote = await NotesModel.findOneAndDelete({
    _id: noteId,
    user: userId,
  });
  logger.debug({ deletedNote: deletedNote?._id }, "Note deleted from DB");

  if (!deletedNote) {
    throw new AppError("Note not found", 404);
  }

  logger.info({ userId, noteId }, "Note deleted successfully");

  return deletedNote.id;
};

export {
  createNoteService,
  getNotesService,
  getNoteService,
  updateNoteService,
  toggleFavoriteService,
  deleteNoteService,
};
